import { SVGProps } from 'react'

/** generated by react-svgr */

const LinkedInIcon = (props: SVGProps<SVGSVGElement>) => (
	<svg
		xmlns='http://www.w3.org/2000/svg'
		width={15}
		height={16}
		fill='#FFF'
		{...props}
	>
		<path d='M13.333.5A1.666 1.666 0 0 1 15 2.167v11.666a1.666 1.666 0 0 1-1.667 1.667H1.667A1.667 1.667 0 0 1 0 13.833V2.167A1.667 1.667 0 0 1 1.667.5h11.666Zm-.416 12.917V9A2.717 2.717 0 0 0 10.2 6.283c-.708 0-1.533.434-1.933 1.084v-.925H5.942v6.975h2.325V9.308a1.163 1.163 0 1 1 2.325 0v4.109h2.325ZM3.233 5.133a1.4 1.4 0 0 0 1.4-1.4 1.405 1.405 0 1 0-1.4 1.4Zm1.159 8.284V6.442H2.083v6.975h2.309Z' />
	</svg>
)

export default LinkedInIcon
